### ISSUE TITLE
No error when Google sign in OAuth consent screen tab is closed

### ISSUE THREAD

**Issue by liyasthomas** [igorjacauna/tauri-firebase-login#1]
Firebase provides proper error codes for `signInWithCredential` authentication function: https://firebase.google.com/docs/reference/js/v8/firebase.auth.Auth#error-codes_10

For example, if I close the OAuth consent screen I would get the proper error code and message. This field is missing.

**Comment by igorjacauna** [comment]
Thanks @liyasthomas, but this repo is just a use case.
